package ExceptionHandling;

public class ThrowKeyword {

	public static void main(String[] args) {
	
		// TODO Auto-generated method stub
		try {
           throw new Exception("some exception is coming");
		}
		catch(Exception e)
		{
			System.out.println("exceptoavkdg");//throw keyword is used generate the own exception
			//throws and throw are passing the rxception.they are not handling the exception		
			}
	}

}
